---
author:              Pavel Tsialnou
category:            Utility
copyright:           (c) 2021 Pavel Tsialnou
dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - cryptonite
description:         Please see the README on GitHub at <https://github.com/paveltsialnou/md5#README.md>
executables:
  md5:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - md5
extra-source-files:
    - README.md
library:
  source-dirs: src
license:             MIT
maintainer:          paveltsialnou@icloud.com
name:                md5
tests:
  tests:
    dependencies:
      - directory
      - md5
      - process
      - QuickCheck
      - quickcheck-instances
    ghc-options:
      - -main-is Test
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main:                QC.hs
    source-dirs:         test
version:             0.1.0.0
